#!/usr/bin/env bash

TAG="${1:-stable}"

cd "${DOMO_HOME}/build/neovim"

# Pull updated tags from the remote
git fetch --tags --force

# Then  switch to the given tag
git checkout "${TAG}"

# Clean up the build directory before regenerating the build files
sudo make distclean

CC=gcc sudo make CMAKE_BUILD_TYPE=RelWithDebInfo

sudo make install
