#!/usr/bin/env bash
#
# Edit scripts interactively (or not)
#
usage="usage: script-edit [SCRIPT]"

if [[ ! -d "${HOME}/scripts" ]]; then
    echo "script-edit: ${HOME}/scripts: no such directory"
    echo "${usage}"
    exit 1
fi

pushd "${HOME}/scripts" &> /dev/null

if [[ -z "${1}" ]]; then
    file="$(fd --type f . | gum filter --placeholder="Filter scripts")"

    [[ -n "${file}" ]] && command "${EDITOR}" "${file}"
else
    if [[ ! -f "${1}" ]]; then
        echo "script-edit: ${1}: no such file"
        echo "${usage}"
        exit 1
    fi

    command "${EDITOR}" "${1}"
fi
