#!/usr/bin/env bash
#
# Switch tmux sessions interactively
#
session="$(tmux list-sessions -F '#S' | gum filter --placeholder="Filter sessions")"
[[ -z "${session}" ]] && exit 0

if [[ -n "${TMUX}" ]]; then
    tmux switch-client -t "${session}"
else
    tmux attach-session -t "${session}"
fi
